{% set version = "0.2.6" %}
{% set kernel_version = "0.0.7" %}

{% if cuda_compiler_version != "None" %}
{% set cuda_major = environ.get("cuda_compiler_version", "11.8").split(".")[0] | int %}
{% else %}
{% set cuda_major = 0 %}
{% endif %}

package:
  name: autoawq
  version: {{ version }}

source:
  - url: https://github.com/casper-hansen/AutoAWQ/archive/refs/tags/v{{ version }}.tar.gz
    sha256: e6a3451d1d4cf69cd81cbb816593d6c4144d323c221354b56d1496afd46ec129
  - url: https://github.com/casper-hansen/AutoAWQ_kernels/archive/refs/tags/v{{ kernel_version }}.tar.gz
    sha256: bae8d0fe5a2aff5112c3270fa2d5a6312d5d5693c214d7174b7ff42d595eb0b9
    folder: kernels

build:
  number: 0
  skip: true  # [cuda_compiler_version == "None"]
  skip: true  # [osx or win]

# break CI jobs per python version
requirements:
  host:
    - python

outputs:
  - name: autoawq_kernels
    version: {{ kernel_version }}
    build:
      activate_in_script: true
      script:
        - sed -i 's/os.environ\["CC"\] = "g++"//' kernels/setup.py
        - sed -i 's/os.environ\["CXX"\] = "g++"//' kernels/setup.py
        - cd kernels
        - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

    requirements:
      build:
        - cmake
        - make
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}
      host:
        - python
        - pip
        - pytorch
        {% if cuda_major >= 12 %}
        - cuda-version {{ cuda_compiler_version }}
        - cuda-cudart-dev
        - libcublas-dev
        - libcusolver-dev
        - libcusparse-dev
        {% endif %}
    test:
      imports:
        - awq_ext

  - name: autoawq
    build:
      script:  {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      build:
      host:
        - python
        - {{ pin_subpackage('autoawq_kernels', exact=True) }}
        - packaging
        - setuptools >=49.4.0
        - pytorch
        - wheel
        - pip
        - requests
        - libxcrypt
      run:
        - python
        - {{ pin_subpackage('autoawq_kernels', exact=True) }}
        - accelerate
        - datasets
        - tokenizers >=0.12.1
        - transformers >=4.35.0
        - typing_extensions >=4.8
        - zstandard
    test:
      imports:
        - awq
      requires:
        - pip
      commands:
        # pending https://github.com/conda-forge/tcolorpy-feedstock/issues/12
        # - pip check

  - name: autoawq-eval
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
        - {{ pin_subpackage('autoawq', exact=True) }}
      run:
        - python >=3.8
        - {{ pin_subpackage('autoawq', exact=True) }}
        - evaluate
        - lm_eval ==0.4.1
        - protobuf
        - scipy
        - tabulate
    test:
      commands:
        - echo "pure metapackage"

about:
  home: https://github.com/casper-hansen/AutoAWQ
  summary: AutoAWQ is an easy-to-use package for 4-bit quantized models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
    - h-vetinari
